### ISSUE TITLE
添加研究生课程

### ISSUE THREAD

**Issue by pangbo13** [SJTU-CSE/awesome-cs#133]
本仓库没有索引计算机系研究生课程，不知可否将研究生课程也添加至此仓库

交大计算机系许多研究生课程与本科课程任务差异很小，研究生课程资料也可为本科生提供参考（反之也成立），故我认为将研究生课程加入本索引，并不会导致混乱

隔壁 @sjtu-cs 组织没有提供类似的索引项目，且该组织已多年未活跃。本项目在交大计算机系学生中较为有名，不少研究生同学也知晓本项目的存在，所以我认为在本项目索引研究生课程会是一个不错的选择。

**Comment by skyzh** [comment]
欢迎 :)
