### ISSUE TITLE
request for CS145实验指导书

### ISSUE THREAD

**Issue by superEason** [SJTU-CSE/awesome-cs#71]
你好，请问是否有CS145: 计算机系统结构实验的指导书，我想跟着要求做一遍

**Comment by skyzh** [comment]
实验指导书属于课程资料，版权归属于交大计算机系系统结构实验中心。如有需求，可以和该课程的老师联系。

http://www.cs.sjtu.edu.cn/PeopleDetail.aspx?id=42

您也可以参考同学的实验报告和结果进行实验。
